export const cities = [
  { value: 'ararica', label: 'Araricá' },
  { value: 'canela', label: 'Canela' },
  { value: 'campo-bom', label: 'Campo Bom' },
  { value: 'dois-irmaos', label: 'Dois Irmãos' },
  { value: 'estancia-velha', label: 'Estância Velha' },
  { value: 'gramado', label: 'Gramado' },
  { value: 'igrejinha', label: 'Igrejinha' },
  { value: 'ivoti', label: 'Ivoti' },
  { value: 'lindolfo-collor', label: 'Lindolfo Collor' },
  { value: 'morro-reuter', label: 'Morro Reuter' },
  { value: 'nova-hartz', label: 'Nova Hartz' },
  { value: 'nova-petropolis', label: 'Nova Petrópolis' },
  { value: 'novo-hamburgo', label: 'Novo Hamburgo' },
  { value: 'parobe', label: 'Parobé' },
  { value: 'picada-cafe', label: 'Picada Café' },
  { value: 'presidente-lucena', label: 'Presidente Lucena' },
  { value: 'riozinho', label: 'Riozinho' },
  { value: 'rolante', label: 'Rolante' },
  { value: 'santa-maria-do-herval', label: 'Santa Maria do Herval' },
  { value: 'sao-leopoldo', label: 'São Leopoldo' },
  { value: 'sapiranga', label: 'Sapiranga' },
  { value: 'taquara', label: 'Taquara' },
  { value: 'tres-coroas', label: 'Três Coroas' },
];
